# Generated by Django 3.2.9 on 2022-07-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.CharField(max_length=200, unique=True)),
                ('short_url', models.CharField(max_length=15, unique=True)),
                ('slag', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
    ]
