# Generated by Django 3.2.9 on 2022-07-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortening', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='slag',
        ),
    ]
